name: Continuous Integration
on:
  - push
  - pull_request

jobs:
  pio-build:
    name: PlatformIO Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.x
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Build
        run: platformio run
      - name: Archive bin
        uses: actions/upload-artifact@v2
        with:
          name: sp140.bin
          path: .pio/build/**/firmware.bin
  generate-uf2:
    name: Generate uf2
    needs: pio-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: sp140.bin
      - uses: actions/checkout@master
      - name: Display info for downloaded files
        run: ls -lh /OpenPPG\ CM0/
