name: Continuous Integration
on:
  - push
  - pull_request

jobs:
  pio-build:
    name: PlatformIO Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.x
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio adafruit-nrfutil
      - name: Build
        run: platformio run
